// Code generated by bpf2go; DO NOT EDIT.
//go:build linux && (arm64be || armbe || mips64be || mipsbe || ppc64 || s390x || sparc64)
// +build linux
// +build arm64be armbe mips64be mipsbe ppc64 s390x sparc64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

//go:embed upf_xdp_bpfeb.o
var upf_xdp_bpfeb_o []byte

type upfXdpPrograms struct {
	UpfXdpIngress *ebpf.Program `ebpf:"upf_xdp_ingress"`
	UpfXdpEgress  *ebpf.Program `ebpf:"upf_xdp_egress"`
}

type upfXdpMaps struct {
	TeidPdrMap     *ebpf.Map `ebpf:"teid_pdr_map"`
	UpfStatsMap    *ebpf.Map `ebpf:"upf_stats_map"`
	UpfForwardMap  *ebpf.Map `ebpf:"upf_forward_map"`
}

type upfXdpObjects struct {
	upfXdpPrograms
	upfXdpMaps
}

func (o *upfXdpObjects) Close() error {
	return closeAll(
		o.UpfXdpIngress,
		o.UpfXdpEgress,
		o.TeidPdrMap,
		o.UpfStatsMap,
		o.UpfForwardMap,
	)
}

type upfXdpSpec struct {
	Programs struct {
		UpfXdpIngress *ebpf.ProgramSpec
		UpfXdpEgress  *ebpf.ProgramSpec
	}
	Maps struct {
		TeidPdrMap    *ebpf.MapSpec
		UpfStatsMap   *ebpf.MapSpec
		UpfForwardMap *ebpf.MapSpec
	}
}

func loadUpfXdpSpec() (*upfXdpSpec, error) {
	spec, err := ebpf.LoadCollectionSpecFromReader(bytes.NewReader(upf_xdp_bpfeb_o))
	if err != nil {
		return nil, fmt.Errorf("can't load upfXdp: %w", err)
	}

	obj := &upfXdpSpec{}
	if err := spec.Assign(obj); err != nil {
		return nil, fmt.Errorf("can't assign upfXdp: %w", err)
	}

	return obj, nil
}

func loadUpfXdpObjects(obj *upfXdpObjects, opts *ebpf.CollectionOptions) error {
	spec, err := loadUpfXdpSpec()
	if err != nil {
		return err
	}
	return spec.LoadAndAssign(obj, opts)
}

func (s *upfXdpSpec) LoadAndAssign(obj *upfXdpObjects, opts *ebpf.CollectionOptions) error {
	coll, err := ebpf.NewCollectionWithOptions(s, opts)
	if err != nil {
		return fmt.Errorf("can't create collection: %w", err)
	}

	if err := coll.Assign(obj); err != nil {
		coll.Close()
		return fmt.Errorf("can't assign to upfXdpObjects: %w", err)
	}

	return nil
}

func closeAll(closers ...io.Closer) error {
	var err error
	for _, c := range closers {
		if c == nil {
			continue
		}
		if closeErr := c.Close(); closeErr != nil && err == nil {
			err = closeErr
		}
	}
	return err
}
